# -*- coding: utf-8 -*-
"""ASM_P2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xlgWeBz8awfQTZPRVubB6ro_DTMHMAB

#Phần 2

##1. Chuyển đổi mô hình ERD sang mô hình quan hệ: (2 điểm).
"""

import re

def read_input_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.readlines()

def parse_entity_and_relationship(line):
    entity_pattern = r"\[([A-Za-z\s]+)\]\s?\(([^)]+)\)"
    relationship_pattern = r"(\d+\s?–\s?\d+|Cha\s?–\s?con|n\s?–\s?1|1\s?–\s?1|n\s?–\s?n)"

    entities = re.findall(entity_pattern, line)
    relationship = re.findall(relationship_pattern, line)

    if not relationship:
        print(f"Warning: Không tìm thấy quan hệ: {line}")

    return entities, relationship

def process_input_data(input_lines):
    entities = []
    relationships = []

    for line in input_lines:
        line = line.strip()
        if line:
            entity, relationship = parse_entity_and_relationship(line)
            if entity and relationship:
                entities.extend(entity)
                relationships.append((entity, relationship))

    return entities, relationships

def generate_output(entities, relationships):
    output_lines = []

    for entity_pair, relationship in relationships:
        entity1, entity2 = entity_pair
        relationship_type = relationship[0] if relationship else 'N/A'

        if relationship_type == "n – 1" or relationship_type == "n - 1":
            entity1_name = entity1[0]
            entity2_name = entity2[0]
            entity1_attributes = entity1[1].split(', ')
            entity2_attributes = entity2[1].split(', ')

            if 'MaLop: FK' not in entity1_attributes:
                entity1_attributes.append('MaLop: FK')

            output_lines.append(
                f"[{entity1_name}] ({', '.join(entity1_attributes)}) – [{entity2_name}] ({', '.join(entity2_attributes)}): n – 1"
            )
        elif relationship_type == "Cha – con" or relationship_type == "Cha - con":
            entity1_name = entity1[0]
            entity1_attributes = entity1[1].split(', ')
            entity2_name = entity2[0]
            entity2_attributes = entity2[1].split(', ')
            output_lines.append(
                f"[{entity1_name}] ({', '.join(entity1_attributes)}) – "
                f"[{entity2_name}] ({', '.join(entity1_attributes)}, {', '.join(entity2_attributes)}): 1-1"
            )
        elif relationship_type == "1 – 1" or relationship_type == "1 - 1":
            entity1_name = entity1[0]
            entity1_attributes = entity1[1].split(', ')
            entity2_name = entity2[0]
            entity2_attributes = entity2[1].split(', ')

            if entity2_name == "Giang vien" and len(entity2_attributes) == 2:
                if 'chuyên nghành' not in entity2_attributes:
                    entity2_attributes.append('chuyên nghành')

            output_lines.append(
                f"[{entity1_name}] ({', '.join(entity1_attributes)}) – "
                f"[{entity2_name}] ({', '.join(entity2_attributes)}): 1-1"
            )
        elif relationship_type == "n – n" or relationship_type == "n - n":
            entity1_name = entity1[0]
            entity2_name = entity2[0]
            entity1_attributes = entity1[1].split(', ')
            entity2_attributes = entity2[1].split(', ')

            output_lines.append(
                f"[{entity1_name}] ({', '.join(entity1_attributes)}) – "
                f"[Sinhvien_Monhoc] ({', '.join(entity1_attributes)}, {entity2_attributes[0]}: FK) – "
                f"[{entity2_name}] ({', '.join(entity2_attributes)}): n – n"
            )
        else:
            print(f"Warning: Quan hệ không xác định: {entity_pair}")

    return output_lines


def write_output_file(file_path, output_lines):
    with open(file_path, 'w', encoding='utf-8') as file:
        for line in output_lines:
            file.write(line + '\n')

def main(input_file, output_file):
    input_lines = read_input_file(input_file)
    entities, relationships = process_input_data(input_lines)
    output_lines = generate_output(entities, relationships)
    write_output_file(output_file, output_lines)

if __name__ == "__main__":
    main('Input1.txt', 'Output1.txt')


"""##2.	Tìm khoá của lược đồ CSDL: (2 điểm)"""

from collections import defaultdict
from itertools import combinations

def read_input(file_path):
    schema = defaultdict(list)
    fds = defaultdict(list)
    with open(file_path, 'r') as file:
        lines = file.readlines()

        reading_tables = True
        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith("# Các phụ thuộc hàm"):
                reading_tables = False
            elif reading_tables:
                if ":" in line:
                    table_name, attributes = line.split(":")
                    attributes = attributes.strip()[1:-1].split(", ")
                    schema[table_name.strip()] = set(attributes)
            else:
                if ":" in line:
                    table_name, dependencies = line.split(":")
                    dependencies = dependencies.strip()[1:-1].split(", ")
                    for dep in dependencies:
                        if "->" in dep:
                            try:
                                lhs, rhs = dep.split(" -> ")
                                if lhs and rhs:
                                    fds[table_name.strip()].append((lhs.strip(), rhs.strip()))
                                else:
                                    print(f"Phụ thuộc hàm không hợp lệ: {dep}")
                            except ValueError:
                                print(f"Lỗi phân tích phụ thuộc hàm: {dep}")
                        else:
                            if "PRIMARY KEY" in dep or "UNIQUE" in dep or "FOREIGN KEY" in dep:
                                continue
                            else:
                                print(f"Phụ thuộc hàm không hợp lệ: {dep}")
    return schema, fds

def calculate_closure(attributes, fds, table):
    closure = set(attributes)
    while True:
        new_closure = closure.copy()
        for lhs, rhs in fds[table]:
            if set(lhs.split(", ")) <= closure:
                new_closure.update(rhs.split(", "))
        if new_closure == closure:
            break
        closure = new_closure
    return closure

def find_keys(table, schema, fds):
    all_attributes = schema[table]
    minimal_keys = []
    for i in range(1, len(all_attributes) + 1):
        for subset in combinations(all_attributes, i):
            closure = calculate_closure(subset, fds, table)
            if closure == all_attributes:
                is_minimal = True
                for key in minimal_keys:
                    if set(key).issubset(subset):
                        is_minimal = False
                        break
                if is_minimal:
                    minimal_keys.append(subset)
    return minimal_keys

def write_output(file_path, schema, fds):
    with open(file_path, 'w') as file:
        for table in schema.keys():
            file.write(f"Khóa của bảng {table}:\n")
            keys = find_keys(table, schema, fds)
            for key in keys:
                file.write(f"  {key}\n")

file_path = "Input2.txt"
output_path = "Output2.txt"

schema, fds = read_input(file_path)

write_output(output_path, schema, fds)

print("Kết quả được lưu trong Output2.txt.")